spring:
  application:
    name: cards
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: ''
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 9000

build:
  version: "3.0"

cards:
  message: "Welcome to EazyBank cards related local APIs "
  contact-details:
    name: "Dragos Lech - Developer"
    email: "dragos@eazybank.com"
  on-call-support:
    - (412) 419-3491
    - (915) 382-1932
