# This is a YAML-formatted file
# Declare variables to be passed into your templates

deploymentName: accounts-deployment
serviceName: accounts
appLabel: accounts
appName: accounts

replicaCount: 2

image:
  repository: marchino/accounts
  tag: s17

containerPort: 8080

service:
  # type: ClusterIP
  type: LoadBalancer
  port: 8080
  targetPort: 8080

appName_enabled: true
profile_enabled: true
config_enabled: true
discovery_enabled: true
resourceserver_enabled: false
otel_enabled: true
kafka_enabled: true
