services:
  accounts:
    image: "marchino/accounts:s4"
    container_name: accounts_ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - eazybytes
  cards:
    image: "marchino/cards:s4"
    container_name: cards_ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - eazybytes
  loans:
    image: "marchino/loans:s4"
    container_name: loans_ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - eazybytes

networks:
  eazybytes:
    driver: bridge

