#!/bin/bash

source $HOME/.sdkman/bin/sdkman-init.sh
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

sdk use java 21.0.3-tem

pushd "$SCRIPT_DIR/accounts" ; mvn clean compile jib:dockerBuild ; popd
pushd "$SCRIPT_DIR/cards" ; mvn clean compile jib:dockerBuild ; popd
pushd "$SCRIPT_DIR/configserver" ; mvn clean compile jib:dockerBuild ; popd
pushd "$SCRIPT_DIR/eurekaserver" ; mvn clean compile jib:dockerBuild ; popd
pushd "$SCRIPT_DIR/gatewayserver" ; mvn clean compile jib:dockerBuild ; popd
pushd "$SCRIPT_DIR/loans" ; mvn clean compile jib:dockerBuild ; popd
