#!/bin/bash

# shellcheck disable=SC1091
source "$HOME/.sdkman/bin/sdkman-init.sh"
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

sdk use java 21.0.3-tem

execute_build() {
    FOLDER="$1"
    pushd "$SCRIPT_DIR/$FOLDER" || exit ; mvn clean compile jib:dockerBuild ; popd || exit
}

execute_build accounts
execute_build cards
execute_build configserver
execute_build eurekaserver
execute_build gatewayserver
execute_build loans
execute_build message
