spring:
  application:
    name: gatewayserver
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
    gateway:
      enabled: true
  info:
    env:
      enabled: true
info:
  app:
    name: gatewayserver
    description: Eazy Bank gateway server application
    version: v1.0.0

logging:
  level:
    '[com.eazybytes.gatewayserver]': debug