spring:
  application:
    name: loans
  config:
    import: "optional:configserver:http://localhost:8071/"
  datasource:
    url: jdbc:mysql://localhost:3307/loansdb
    username: root
    password: root
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 8090
