spring:
  application:
    name: loans
  config:
    import: "optional:configserver:http://localhost:8071/"
  datasource:
    url: jdbc:h2:mem:loansdb
    username: sa
    password: password
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
  cloud:
    kubernetes:
      discovery:
        all-namespaces: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
    shutdown:
      enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

server:
  port: 8090

info:
  app:
    name: loans
    description: Eazy Bank loans application
    version: v1.0.0

logging:
  level:
    '[com.eazybytes.loans]': debug
  pattern:
    level: '%5p [${spring.application.name}.%X{trace_id}.%X{span_id}]'

