build:
  version: "2.0"

cards:
  message: "Welcome to EazyBank cards related QA APIs "
  contact-details:
    name: "Cherryl Pankaj - QA Lead"
    email: "cherryl@eazybank.com"
  on-call-support:
    - (310) 875-4367
    - (201) 236-1267
