spring:
  application:
    name: accounts
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: ''
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8080

build:
  version: "1.0"

accounts:
  message: Welcome to EazyBank accounts related local APIs
  contact-details:
    name: "John Doe - Developer"
    email: "john@eazybank.com"
  on-call-support:
    - (555) 555-1234
    - (555) 523-1345
