services:
  network-deploy-service:
    networks:
      - eazybank
  microservice-base-config:
    extends:
      service: network-deploy-service
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_RABBITMQ_HOST: rabbit
    deploy:
      resources:
        limits:
          memory: 700m
  microservice-configserver-config:
    extends:
      service: microservice-base-config
    environment:
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
    depends_on:
      configserver:
        condition: service_healthy