services:
  rabbit:
    image: "rabbitmq:3.13-management"
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: "rabbitmq-diagnostics check_port_connectivity"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    extends:
      file: common-config.yml
      service: network-deploy-service
  configserver:
    image: "marchino/configserver:s6"
    container_name: configserver_ms
    ports:
      - "8071:8071"
    depends_on:
      rabbit:
        condition: service_healthy
    healthcheck:
      test: "wget --no-verbose -q --tries=1 -O- localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config
    environment:
      SPRING_PROFILES_ACTIVE: git
  accounts:
    image: "marchino/accounts:s6"
    container_name: accounts_ms
    ports:
      - "8080:8080"
#    environment:
#      SPRING_APPLICATION_NAME: accounts
    extends:
      file: common-config.yml
      service: microservice-configserver-config
  cards:
    image: "marchino/cards:s6"
    container_name: cards_ms
    ports:
      - "9000:9000"
    extends:
      file: common-config.yml
      service: microservice-configserver-config
#    environment:
#      SPRING_APPLICATION_NAME: cards
  loans:
    image: "marchino/loans:s6"
    container_name: loans_ms
    ports:
      - "8090:8090"
    extends:
      file: common-config.yml
      service: microservice-configserver-config
#    environment:
#      SPRING_APPLICATION_NAME: loans

networks:
  eazybank:
    driver: bridge

