services:
  accountsdb:
    container_name: accountsdb
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: accountsdb
    extends:
      file: common-config.yml
      service: microservice-db-config
    volumes:
      - accountsdb-data:/var/lib/mysql
  loansdb:
    container_name: loansdb
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: loansdb
    extends:
      file: common-config.yml
      service: microservice-db-config
    volumes:
      - loansdb-data:/var/lib/mysql
  cardsdb:
    container_name: cardsdb
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: cardsdb
    extends:
      file: common-config.yml
      service: microservice-db-config
    volumes:
      - cardsdb-data:/var/lib/mysql
  redis:
    container_name: redis
    image: "redis:7.4-alpine"
    healthcheck:
      test: "redis-cli ping"
      interval: 2s
      timeout: 5s
      retries: 10
      start_period: 2s
    ports:
      - "6379:6379"
    extends:
      file: common-config.yml
      service: network-deploy-service
  configserver:
    image: "marchino/configserver:s6"
    container_name: configserver_ms
    ports:
      - "8071:8071"
    healthcheck:
      test: "wget --no-verbose -q --tries=1 -O- localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config
    environment:
      SPRING_PROFILES_ACTIVE: git
  eurekaserver:
    image: "marchino/eurekaserver:s8"
    container_name: eurekaserver_ms
    ports:
      - "8070:8070"
    healthcheck:
      test: "wget --no-verbose -q --tries=1 -O- localhost:8070/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-configserver-config
    environment:
      SPRING_PROFILES_ACTIVE: git
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
    depends_on:
      configserver:
        condition: service_healthy
  accounts:
    image: "marchino/accounts:s10"
    container_name: accounts_ms
    healthcheck:
      test: "wget --no-verbose -q --tries=1 -O- localhost:8080/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://accountsdb:3306/accountsdb
    extends:
      file: common-config.yml
      service: microservice-eureka-config
    depends_on:
      accountsdb:
        condition: service_healthy
  cards:
    image: "marchino/cards:s10"
    container_name: cards_ms
    healthcheck:
      test: "wget --no-verbose -q --tries=1 -O- localhost:9000/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-eureka-config
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://cardsdb:3306/cardsdb
    depends_on:
      cardsdb:
        condition: service_healthy
  loans:
    image: "marchino/loans:s10"
    container_name: loans_ms
    healthcheck:
      test: "wget --no-verbose -q --tries=1 -O- localhost:8090/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-eureka-config
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://loansdb:3306/loansdb
    depends_on:
      loansdb:
        condition: service_healthy
  gatewayserver:
    image: "marchino/gatewayserver:s10"
    container_name: gatewayserver_ms
    ports:
      - "8072:8072"
    extends:
      file: common-config.yml
      service: microservice-eureka-config
    environment:
      SPRING_DATA_REDIS_HOST: redis
    depends_on:
      accounts:
        condition: service_healthy
      cards:
        condition: service_healthy
      loans:
        condition: service_healthy
      redis:
        condition: service_healthy

networks:
  eazybank:
    driver: bridge

volumes:
  accountsdb-data:
  loansdb-data:
  cardsdb-data:
