pspring:
  application:
    name: configserver
  profiles:
    active:
      - native
#      - git
  cloud:
    config:
      server:
        native:
#          search-locations: "classpath:/config"
          search-locations: "file://${HOME}/wsl_workspace/utility/udemy/learn-develop-microservices-with-java-spring-boot/config/"
        git:
          uri: https://github.com/alessandro-marchino/learn-develop-microservices-with-java-spring-boot.git
          default-label: master
          timeout: 5
          clone-on-start: true
          force-pull: true
          search-paths:
            - config
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
encrypt:
  key: 45D81EC1EF61DF9AD8D3E5BB3979
server:
  port: 8071
