build:
  version: "3.0"

cards:
  message: "Welcome to EazyBank cards related local APIs "
  contact-details:
    name: "Dragos Lech - Developer"
    email: "dragos@eazybank.com"
  on-call-support:
    - (412) 419-3491
    - (915) 382-1932
