build:
  version: "1.0"

loans:
  message: "Welcome to EazyBank loans related prod APIs"
  contact-details:
    name: "Pelias Sudhir - Product Owner"
    email: "pelias@eazybank.com"
  on-call-support:
    - (723) 656-8709
    - (156) 342-0956

spring:
  datasource:
    url: jdbc:h2:mem:loansdb
    username: sa
    password: password
  h2:
    console:
      enabled: false
      settings:
        web-allow-others: true
