build:
  version: "3.0"

loans:
  message: "Welcome to EazyBank loans related local APIs "
  contact-details:
    name: "Amaal Grega - Developer"
    email: "amaal@eazybank.com"
  on-call-support:
    - (452) 456-2176
    - (546) 764-8934
