apiVersion: apps/v1
kind: Deployment
metadata:
  name: eurekaserver-deployment
  labels:
    name: eurekaserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eurekaserver
  template:
    metadata:
      labels:
        app: eurekaserver
    spec:
      containers:
      - name: eurekaserver
        image: marchino/eurekaserver:s12
        env:
          - name: SPRING_APPLICATION_NAME
            valueFrom:
              configMapKeyRef:
                key: EUREKA_APPLICATION_NAME
                name: eazybank-configmap
          - name: SPRING_CONFIG_IMPORT
            valueFrom:
              configMapKeyRef:
                key: SPRING_CONFIG_IMPORT
                name: eazybank-configmap
        resources:
          limits:
            memory: "512Mi"
            cpu: "2"
        ports:
        - containerPort: 8070
---
apiVersion: v1
kind: Service
metadata:
  name: eurekaserver
  labels:
    app: eurekaserver
spec:
  selector:
    app: eurekaserver
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8070
    targetPort: 8070
