apiVersion: apps/v1
kind: Deployment
metadata:
  name: loans-deployment
  labels:
    name: loans
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loans
  template:
    metadata:
      labels:
        app: loans
    spec:
      containers:
      - name: loans
        image: marchino/loans:s12
        env:
          - name: SPRING_APPLICATION_NAME
            valueFrom:
              configMapKeyRef:
                key: LOANS_APPLICATION_NAME
                name: eazybank-configmap
          - name: SPRING_PROFILES_ACTIVE
            valueFrom:
              configMapKeyRef:
                key: SPRING_PROFILES_ACTIVE
                name: eazybank-configmap
          - name: SPRING_CONFIG_IMPORT
            valueFrom:
              configMapKeyRef:
                key: SPRING_CONFIG_IMPORT
                name: eazybank-configmap
          - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
            valueFrom:
              configMapKeyRef:
                key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
                name: eazybank-configmap
        resources:
          limits:
            memory: "512Mi"
            cpu: "2"
        ports:
        - containerPort: 8090
---
apiVersion: v1
kind: Service
metadata:
  name: loans
  labels:
    app: loans
spec:
  selector:
    app: loans
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8090
    targetPort: 8090
