apiVersion: apps/v1
kind: Deployment
metadata:
  name: gatewayserver-deployment
  labels:
    name: gatewayserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gatewayserver
  template:
    metadata:
      labels:
        app: gatewayserver
    spec:
      containers:
      - name: gatewayserver
        image: marchino/gatewayserver:s12
        env:
          - name: SPRING_APPLICATION_NAME
            valueFrom:
              configMapKeyRef:
                key: GATEWAY_APPLICATION_NAME
                name: eazybank-configmap
          - name: SPRING_CONFIG_IMPORT
            valueFrom:
              configMapKeyRef:
                key: SPRING_CONFIG_IMPORT
                name: eazybank-configmap
          - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
            valueFrom:
              configMapKeyRef:
                key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
                name: eazybank-configmap
          - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI
            valueFrom:
              configMapKeyRef:
                key: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI
                name: eazybank-configmap
        resources:
          limits:
            memory: "512Mi"
            cpu: "2"
        ports:
        - containerPort: 8072
---
apiVersion: v1
kind: Service
metadata:
  name: gatewayserver
spec:
  selector:
    app: gatewayserver
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8072
    targetPort: 8072
