global:
  configMapName: eazybank-dev-configmap
  activeProfile: git,k8s
  configServerURL: configserver:http://configserver.default.svc.cluster.local:8071/
  discoveryServerUrl: http://spring-cloud-kubernetes-discoveryserver.default.svc.cluster.local:80
  keyCloakURL: http://keycloak.default.svc.cluster.local:7080/realms/master/protocol/openid-connect/certs
  openTelemetryJavaAgent: "-javaagent:/app/libs/opentelemetry-javaagent-1.33.5.jar"
  otelExporterEndpoint: http://tempo-grafana-tempo-distributor.default.svc.cluster.local:4317
  otelMetricsExporter: none
  kafkaBrokerURL: kafka-controller-0.kafka-controller-headless.default.svc.cluster.local:9092
