services:
  network-deploy-service:
    networks:
      - eazybank
  microservice-db-config:
    extends:
      service: network-deploy-service
    image: "mysql:8.0.21"
    environment:
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: "mysqladmin ping -h localhost"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
  microservice-base-config:
    extends:
      service: network-deploy-service
    environment:
      SPRING_PROFILES_ACTIVE: prod
    deploy:
      resources:
        limits:
          memory: 700m
  microservice-configserver-config:
    extends:
      service: microservice-base-config
    environment:
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      configserver:
        condition: service_healthy
  microservice-eureka-config:
    extends:
      service: microservice-configserver-config
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
    depends_on:
      eurekaserver:
        condition: service_healthy
